#!/bin/bash
#Tecan
#Description: based on http://elephly.net/posts/2013-10-01-dm-crypt.html https://weichselbraun.net/manual/encrypted_dvd/encrypted_dvd.html
#I personally use a 2048-bit key, and find that my CPU can keep up with the maximum bandwidth of my SATA drive with no problems. I'd recommend a 2048 on any modern hardware (1GHz or faster processor). -Josh Glover

#oauth server

#reiserfs option
#csb=cryptsetup
#csb=cryptsetup2
csb=cryptsetup
mountpoint=EDISK-mount
imagename=EDISK-tmp.iso
mapper=EDISK-Device
mountdir=/dev/mapper/

dir=$(pwd)
uid=$(id -u)
gid=$(id -g)


dir=$(pwd)
echo "would you like to make a new image y/n"
read loading
#zenity drag and drop ?
if [ $loading == y ];then 
    #if the imagename exists then these 2 lines can be skipped
    dd if=/dev/zero bs=1M count=650 of="$dir/$imagename" #665-safe 700-max cdr , 4587.45-safe max-4700 dvd or 8298.4-safe max-8500 dvd-DL
    sudo $csb luksFormat "$dir/$imagename" #since this is used this is not needed -  growisofs -dvd-compat -Z /dev/sr0=image.iso
    sudo $csb luksOpen "$dir/$imagename" $mapper
    #expect YES
    #palindromeDVD expect enter password : encryptedDVD12
    sudo ./mkfs.ext4 -t ext4 "/dev/mapper/$mapper"
    sudo mount "/dev/mapper/$mapper" "$dir/$mountpoint"
    #sudo mount -t ext4 -o uid=$uid,gid=$gid "/dev/mapper/$mapper" "$dir/$mountpoint"
    sudo chown $USER "$dir/$mountpoint/" -R
    mkdir "$dir/$mountpoint"
else
    sudo $csb luksOpen "$dir/$imagename" $mapper
    sudo mount "/dev/mapper/$mapper" "$dir/$mountpoint"
fi
echo pause before unmounting and closing
read
sudo umount "$dir/$mountpoint"
sudo $csb luksClose $mapper
#keyctl unlink

#cdrecord -v -dao dev=/dev/sr0 speed=16 "$dir/$imagename"

#sudo chown [your name session] my-mount-point



#mkfs.reiserfs /dev/loop0 
#mount -t reiserfs /dev/loop0 /media/private/
#umount /media/private/
#losetup -d /dev/loop0

#modprobe cryptoloop
#modprobe aes
#losetup -e aes /dev/loop0 /dev/sda3
#mount -t reiserfs /dev/loop0 /media/private/
#dd if=/dev/zero of=/root/private bs=1024M count=1
#shred -v -n 1 /root/private 




#    dd if=/dev/zero of=dvd.img bs=1000000 count=4700

#Mount the image on a loopback device and prepare it for further use with LUKS:

#    losetup /dev/loop0 dvd.img
#    cryptsetup -c aes-cbc-essiv:sha256 -y -s 256 luksFormat /dev/loop0

#Open the encrypted device with cryptsetup and create the file system.

#    cryptsetup luksOpen /dev/loop0 dvd
#    mkudffs --media-type=dvd /dev/mapper/dvd

#Mount the device (you'll have to remount it in read-write mode).

#   mount /dev/mapper/dvd /media/dvd
#   mount -o remount,rw /media/dvd

#Now copy your data to the DVD (/media/dvd)

#Close the devicemapper crypto device and the loopback device

#   cryptsetup luksClose dvd
#   losetup -d /dev/loop0

